givtnl/givt-app

android/app/src/main/AndroidManifest.xml
ios/Runner/Info.plist
lib/app.dart
lib/features/give/bloc/organisation/organisation_bloc.dart
lib/features/give/models/webview_input.dart
lib/features/give/pages/giving_page.dart
lib/features/give/pages/home_page.dart
lib/shared/widgets/splash_screen.dart

This pr is addressing the issue that we had with the webview and overriding of the buttons with JS. Instead we are using the InAppBrowser (which is a browser) and we are listening when the "natived" url is being called to pop up the screen to the home page. 
"natived" is in the url when the close or cancel (OK in the popup) are tapped.
[More here](https://inappwebview.dev/docs/in-app-browsers/in-app-browser)

fix: webview

---

lib/features/give/widgets/numeric_keyboard.dart

Improvements on the presets + made fontsize smaller on small screen

Improvements on the presets (BFF-1299 + BFF-1389)

---

lib/shared/models/user_ext.dart

Set notificationid when temp account is transformed to registered

PushnotificationId is not send to our db when user account is created (BFF-1456)

---

lib/features/give/pages/bt_scan_page.dart

Prevent the bluetooth search to call the "start()" method again. Therefore, the search should stop whenever the page is disposed.

BFF-1461 Stop searching for BT devices when page is disposed

---

lib/core/network/api_service.dart
lib/features/auth/cubit/auth_cubit.dart

Use the guid passed through the method arguments instead of using the one from the state as the one from the state could be empty

BFF-1463 Use the guid passed through the method

---

ios/Runner/AppDelegate.swift
lib/core/notification/notification_service.dart

There was a setup missed for iOS where the delegate had to be initialized to communicate when on background and the onDidReceive notifcation tap had to be initialized in the DarwinInit

BFF-1474 Adjusted the notification setup for iOS to redirect the user

---

lib/core/logging/logging_service.dart

Switched the Intl package method with the platform locale name. 
According to the [documentation](https://api.flutter.dev/flutter/dart-io/Platform/localeName.html) this takes the device current locale. However, on Android devices seems a bit tricky. 
I would like to avoid using a "global" context as we use this logging everywhere in the code and by using context would pollute the code quite a lot.

BFF-1493 Switched the intl locale with the Platform locale name

---

lib/features/give/pages/bt_scan_page.dart

Set the appbar and scafold background to #FBFBFB color as the GIF background is not white as we assumed at the beggining.

BFF-958 Set the background color of the scafold to #FBFBFB

---

lib/features/give/repositories/campaign_repository.dart

Check that the name of the organization from the last donation remembered in shared preferences is the same as the name in the cached list of orgs.

Bug: kids-329 wrong org name on beacon screen

---

Makefile
README.md

With features such as flavors and Melos, I've noticed that the app contains several commands that can be shortened with a Makefile. This PR provides a simple quality-of-life feature for app contributors and incentivizes more frequent usage of other commands like `make lint`, which may assist with keeping track and following Flutter's linter rules.

Feat: adds Makefile support

---

lib/features/give/pages/bt_scan_page.dart

- I added a dialog to be displayed when the iOS user has the BT off and unauthorized

BFF-1422 Display dialog when BT is OFF 

---

lib/app/routes/app_router.dart
lib/features/auth/cubit/auth_cubit.dart
lib/features/auth/cubit/auth_state.dart
lib/features/auth/pages/login_page.dart
lib/features/permit_biometric/pages/permit_biometric_page.dart
lib/utils/auth_utils.dart

The new biometricCheck AuthStatus and logic based on it is implemented (KIDS-748)

---

lib/features/children/generosity_challenge/cubit/generosity_challenge_cubit.dart
lib/features/children/generosity_challenge/cubit/generosity_challenge_state.dart
lib/features/children/generosity_challenge/pages/generosity_challenge_overview.dart

Toggle challenge time difference days vs minutes

---

lib/features/children/generosity_challenge/repositories/generosity_challenge_repository.dart

Should fix:
https://console.firebase.google.com/u/0/project/givtapp-ebde1/crashlytics/app/android:net.givtapp.droid2/issues/f0e51be3c8ddbb9304c9043cb41d9d6d?time=last-twenty-four-hours&versions=4.2.14%20(483)&sessionEventKey=6641E0BB00EA00033277DE639BB34797_1946863832000665782

Fix generosity repo crashing on loading from cache.

---

assets/jsons/generosity_challenge/chat_scripts/chat_script_day_7.json
lib/features/children/generosity_challenge_chat/chat_scripts/dialogs/chat_confetti_dialog.dart
lib/features/children/generosity_challenge_chat/chat_scripts/models/enums/chat_script_function.dart
lib/features/children/generosity_challenge_chat/chat_scripts/widgets/chat_bubble.dart
lib/features/children/generosity_challenge_chat/chat_scripts/widgets/chat_picture.dart

- Final day chat is implemented; 
- Confetti function is implemented;

Day 8 chat is implemented (KIDS-954)

---

lib/app/injection/injection.dart
lib/features/children/generosity_challenge/cubit/generosity_challenge_vpc_setup_cubit.dart
lib/features/children/generosity_challenge/pages/generosity_challenge_vpc_setup_page.dart
lib/features/children/generosity_challenge/repositories/generosity_challenge_vpc_repository.dart
lib/features/children/generosity_challenge/utils/generosity_challenge_content_helper.dart
lib/features/children/generosity_challenge/widgets/generosity_challenge_daily_card.dart

Feature: finishing touch generosity challenge

---

lib/features/give/pages/bt_scan_page.dart

To solve the most common error in Firebase:
https://console.firebase.google.com/u/0/project/givtapp-ebde1/crashlytics/app/android:net.givtapp.droid2/issues/d04ed96fc4a8389988c5a59193694665?time=last-ninety-days&types=crash&sessionEventKey=66752E82021600015597253511A19829_1961303981121908895

Show message to android user if we can't turn on bluetooth automatically (KIDS-1113)

---

lib/features/family/features/profiles/repository/profiles_repository.dart

When refetching a child we should also refetch all the profiles.

Bug: Manage family screen is not updated after topup (KIDS-1306)

---

lib/features/family/features/profiles/cubit/profiles_cubit.dart
lib/features/family/features/profiles/repository/profiles_repository.dart
lib/features/family/features/reflect/bloc/interview_cubit.dart
lib/features/family/features/reflect/presentation/pages/record_answer_screen.dart
lib/features/family/features/reflect/presentation/widgets/animated_arc.dart

- Prevent some uncaught exceptions because of async stuff (Future.delayed) which is still running
- Also removed a double emitting loadingstate because it was keeping yuo in the loop at startup (well.. I think, hard to debug) 
- Also fixed a bug if you want to play the game multiple times

Small improvements / fixes

---

lib/features/children/add_member/pages/add_member_counter_page.dart

Maybe not the best solution, but prevents error screen

Disable going back from first time set up family

---

lib/features/family/app/injection.dart
lib/features/family/features/league/bloc/league_cubit.dart
lib/features/family/features/league/presentation/pages/league_screen.dart
lib/features/family/features/league/presentation/pages/models/league_screen_uimodel.dart
lib/features/family/features/league/presentation/widgets/empty_league.dart

- Add logic to determine if user should see Generosity Hunt or Gratitude Game
- Modify LeagueCubit to access ImpactGroupsRepository and check church preference
- Update LeagueScreenUIModel to include showGenerosityHunt parameter
- Modify EmptyLeague widget to display different text and navigation based on game type
- Update LeagueScreen to pass game type information to EmptyLeague widget
- Update dependency injection to include ImpactGroupsRepository in LeagueCubit
Users with Redeemer church preference now see 'Generosity Hunt' content instead of 'Gratitude Game' content on the League page.

fix(COR-582): Change League welcome screen based on game type
