givtnl/givt-app

- lib/features/first_use/pages/welcome_page.dart
> Fixed issue for welcome page

- lib/features/auth/pages/email_signup_page.dart
> fix: BFF-704 Added continue button validation

- android/app/src/main/AndroidManifest.xml
- lib/features/give/pages/giving_page.dart
- lib/features/give/widgets/choose_amount.dart
- pubspec.lock
- pubspec.yaml
This is a quick solution that I found for transactions. It's not the best and I am sure it can be better
> feat: BFF-596

- ios/Runner/Info.plist
- ios/fastlane/Fastfile
> fix:BFF-714 Added Camera and location usage description

- lib/features/give/bloc/give/give_bloc.dart
- lib/features/give/pages/qr_code_scan_page.dart
- lib/shared/widgets/custom_navigation_drawer.dart
- pubspec.lock
- pubspec.yaml
Fix for qr code page crash on android
> fix: qr code

- android/app/src/main/AndroidManifest.xml
- lib/features/give/widgets/choose_amount.dart
- lib/features/give/widgets/collection_form_field.dart
> fix : collection fields

- .vscode/launch.json
- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- lib/features/give/bloc/give/give_bloc.dart
- pubspec.lock
> fix: bluetooth android

- lib/features/give/widgets/numeric_keyboard.dart
> Fix: buttons keyboard buttons on smaller screen

- lib/features/give/pages/giving_page.dart
> Fixed toolbar

- .github/workflows/android.yml
> Updated android release track to beta-flutter

- pubspec.yaml
> Bump version of the app to 3.17.0

- lib/shared/models/user_ext.dart
> fix: appLanguage is nullable

- lib/utils/app_theme.dart
> Smaller font

- lib/shared/models/user_ext.dart
> fix: IBAN is nullable

- lib/features/give/widgets/choose_amount.dart
- lib/features/give/widgets/numeric_keyboard.dart
> Choose Amount UI Improvements

- lib/features/auth/pages/email_signup_page.dart
- lib/features/auth/pages/login_page.dart
- lib/features/first_use/pages/welcome_page.dart
- lib/features/give/pages/home_page.dart
> space around login/signup screens

- lib/features/give/widgets/choose_amount.dart
- lib/features/give/widgets/collection_form_field.dart
- lib/features/give/widgets/numeric_keyboard.dart
> bugfix + some small ui improvements

- android/fastlane/Fastfile
> fix: Match build number with latest on play store

- pubspec.yaml
> fix: Match Play Store build number

- lib/core/network/api_service.dart
> fix: remote the development variable from api service

- lib/features/give/pages/home_page.dart
> Removed question mark

- .github/workflows/mergegatekeeper.yaml
> add merge gatekeeper

- lib/features/auth/widgets/terms_and_conditions_dialog.dart
- lib/features/give/pages/home_page.dart
- lib/features/registration/pages/personal_info_page.dart
- lib/features/registration/pages/signup_page.dart
- lib/shared/dialogs/dialogs.dart
- lib/shared/dialogs/faq_bottom_sheet.dart
- lib/utils/app_theme.dart
Added FAQ and Fixed bug for auto selection of country
> feat: bff 627 FAQ 

- lib/features/registration/pages/bacs_explanation_page.dart
> feat: BFF-627 Added help for bacs

- lib/app.dart
- lib/features/auth/cubit/auth_cubit.dart
- lib/shared/bloc/infra/infra_cubit.dart
- lib/shared/models/user_ext.dart
> fix:BFF-866 Check for platform

- lib/core/network/api_service.dart
- lib/features/unregister_account/cubit/unregister_cubit.dart
- lib/features/unregister_account/cubit/unregister_state.dart
- lib/features/unregister_account/unregister_page.dart
> fix: bff 631/terminate account

- android/app/build.gradle
- lib/core/network/country_iso_info.dart
- pubspec.lock
- pubspec.yaml
> fix: Changed location package

- lib/features/give/widgets/collection_form_field.dart
> fix: fixed lowerLimit

- lib/features/give/bloc/give/give_bloc.dart
- lib/features/give/pages/gps_scan_page.dart
- lib/features/give/pages/organization_list_page.dart
> fix: bff 893/donation screen

- lib/features/auth/pages/email_signup_page.dart
- lib/features/give/pages/home_page.dart
- lib/features/give/pages/select_giving_way_page.dart
- lib/features/give/widgets/context_list_tile.dart
- lib/features/registration/pages/signup_page.dart
- lib/shared/dialogs/faq_bottom_sheet.dart
- lib/shared/widgets/custom_navigation_drawer.dart
> Bff 845 visual improvements

- lib/app/routes/app_router.dart
- lib/features/auth/pages/change_password_page.dart
- lib/features/give/bloc/give/give_bloc.dart
- lib/features/give/pages/giving_page.dart
- lib/features/give/pages/gps_scan_page.dart
- lib/features/give/pages/home_page.dart
- lib/features/give/pages/qr_code_scan_page.dart
- lib/features/give/pages/select_giving_way_page.dart
- lib/features/give/pages/success_offline_donation_page.dart
- lib/features/give/widgets/choose_amount.dart
- lib/features/give/widgets/collection_form_field.dart
- lib/features/give/widgets/context_list_tile.dart
- lib/features/registration/pages/bacs_explanation_page.dart
- lib/features/registration/pages/mandate_explanation_page.dart
- lib/features/registration/pages/sign_bacs_mandate_page.dart
- lib/features/registration/pages/sign_sepa_mandate_page.dart
- lib/utils/app_theme.dart
> fix: Color fixes

- .github/workflows/android.yml
- .github/workflows/ios.yml
- .github/workflows/main.yaml
- .vscode/launch.json
- android/fastlane/Fastfile
- ios/fastlane/Fastfile
- lib/app/bootstrap.dart
- lib/app/injection/injection.dart
- lib/core/logging/log_message.dart
- lib/core/logging/logging.dart
- lib/core/logging/logging_service.dart
- lib/core/network/interceptor.dart
- lib/core/network/network.dart
- lib/features/auth/cubit/auth_cubit.dart
- lib/features/give/bloc/give/give_bloc.dart
- lib/features/give/bloc/organisation/organisation_bloc.dart
- lib/features/give/pages/giving_page.dart
- lib/features/give/widgets/choose_amount.dart
- lib/features/give/widgets/collection_form_field.dart
- lib/features/registration/bloc/registration_bloc.dart
- lib/features/unregister_account/cubit/unregister_cubit.dart
- lib/main_development.dart
- lib/main_production.dart
- lib/main_staging.dart
- lib/shared/bloc/infra/infra_cubit.dart
- lib/shared/bloc/remote_data_source_sync/remote_data_source_sync_bloc.dart
- lib/shared/models/user_ext.dart
- pubspec.lock
- pubspec.yaml
> feat: bff 903/logit kibana

- .github/workflows/android.yml
- .github/workflows/ios.yml
> fix: BFF-902 require workflow secret

- android/fastlane/Fastfile
> BFF-902 added urls from env

- lib/features/give/pages/home_page.dart
- lib/features/give/widgets/choose_amount.dart
> fix: Reset controllers based on given value

- pubspec.yaml
> Updated to 3.18.0 version

- lib/core/network/api_service.dart
- lib/features/overview/bloc/givt_bloc.dart
- lib/features/overview/bloc/givt_event.dart
- lib/features/overview/bloc/givt_state.dart
- lib/features/overview/models/givt.dart
- lib/features/overview/pages/overview_page.dart
- lib/features/overview/widgets/givt_list_item.dart
- lib/shared/bloc/infra/infra_cubit.dart
- lib/shared/dialogs/confirmation_dialog.dart
- lib/shared/dialogs/dialogs.dart
- lib/shared/repositories/givt_repository.dart
> fix: Givts GiftAid

- lib/features/registration/pages/signup_page.dart
> align policy text left

- lib/features/registration/pages/signup_page.dart
> disabled field is grey

- lib/features/overview/pages/overview_page.dart
> fix: Display info button when there are givts

- lib/features/auth/cubit/auth_cubit.dart
- lib/features/auth/cubit/auth_state.dart
- lib/features/auth/pages/change_password_page.dart
- lib/shared/widgets/custom_navigation_drawer.dart
> fix: bff 942/change password

- lib/features/account_details/pages/personal_info_edit_page.dart
> fix: BFF-940 Not display arrow when on tap is null

- lib/features/give/pages/bt_scan_page.dart
- lib/features/give/pages/giving_page.dart
- lib/features/registration/pages/signup_page.dart
> fix: bff 912/browser

- lib/app/routes/app_router.dart
- lib/core/logging/logging_service.dart
- lib/features/give/pages/select_giving_way_page.dart
- lib/features/give/pages/success_offline_donation_page.dart
- lib/shared/repositories/givt_repository.dart
> fix: BFF-849 Send offline givts if there are any on the next donation

- .github/workflows/android.yml
- .github/workflows/ios.yml
> Revert "Bump maierj/fastlane-action from 2.3.0 to 3.0.0"

- .github/workflows/android.yml
- .github/workflows/ios.yml
> Revert "Bump ruby/setup-ruby from 1.118.0 to 1.152.0"

- lib/core/enums/country.dart
- lib/features/give/pages/home_page.dart
- lib/features/give/widgets/choose_amount.dart
- lib/shared/dialogs/warning_dialog.dart
> feat: BFF-890 Implemented dialog for lower and maximum amount

- lib/features/auth/cubit/auth_cubit.dart
> fix: BFF-942 Removed auth success check

- lib/core/network/api_service.dart
- lib/features/give/bloc/give/give_bloc.dart
- lib/features/give/bloc/give/give_state.dart
- lib/features/give/pages/giving_page.dart
- lib/features/give/pages/gps_scan_page.dart
- lib/features/give/pages/select_giving_way_page.dart
- lib/shared/models/collect_group.dart
- lib/shared/models/location.dart
- lib/shared/models/qr_code.dart
- lib/shared/repositories/collect_group_repository.dart
This pr contains the inactive beacon state. As that wasn't addressed before
> fix: bff 902/instance

- lib/features/auth/pages/email_signup_page.dart
- lib/utils/util.dart
> fix: BFF-969 Replaced email regex

- lib/features/auth/pages/email_signup_page.dart
- lib/features/give/bloc/give/give_bloc.dart
- lib/features/give/pages/select_giving_way_page.dart
- lib/shared/widgets/custom_navigation_drawer.dart
- lib/utils/util.dart
> fix: bff 955/beacon instance name

- lib/features/give/bloc/give/give_bloc.dart
> BFF-955 Fetch instance name

- lib/features/give/bloc/give/give_bloc.dart
> BFF-955 Fetch instance name on code scanned out of the app

- lib/core/auth/local_auth_info.dart
- lib/features/auth/cubit/auth_cubit.dart
- lib/features/auth/cubit/auth_state.dart
- lib/features/first_use/pages/welcome_page.dart
- lib/shared/pages/fingerprint_bottom_sheet.dart
- lib/shared/widgets/custom_navigation_drawer.dart
> fix: bff 643/touch

- lib/core/network/api_service.dart
- lib/features/overview/bloc/givt_bloc.dart
- lib/features/overview/bloc/givt_event.dart
- lib/features/overview/bloc/givt_state.dart
- lib/features/overview/pages/overview_page.dart
- lib/features/overview/widgets/dropdown_year_menu.dart
- lib/features/overview/widgets/widgets.dart
- lib/shared/repositories/givt_repository.dart
Added a download button to the AppBar on donations-history.
It builds a bottom sheet where you can pick a year, and request your yearly overview.
This is an api call. The actual overview is sent to your email.
> BFF 646 Build download yearly overview feature

- lib/features/account_details/bloc/personal_info_edit_bloc.dart
- lib/features/account_details/bloc/personal_info_edit_event.dart
- lib/features/give/pages/home_page.dart
- lib/features/give/widgets/choose_amount.dart
- lib/shared/pages/change_max_amount_bottom_sheet.dart
- lib/shared/pages/pages.dart
- lib/shared/widgets/custom_navigation_drawer.dart
- lib/utils/auth_utils.dart
- lib/utils/util.dart
- lib/utils/utils.dart
> feat: bff 654/max amount

- pubspec.lock
- pubspec.yaml
> Revert "Bump flutter_blue_plus from 1.8.7 to 1.10.5"

- .github/workflows/android.yml
- .github/workflows/ios.yml
- .vscode/launch.json
- android/fastlane/Fastfile
- ios/fastlane/Fastfile
- lib/app/injection/injection.dart
- lib/core/network/api_service.dart
- lib/features/overview/bloc/givt_bloc.dart
- lib/features/overview/pages/overview_page.dart
- lib/features/overview/widgets/download_year_donation.dart
- lib/shared/repositories/givt_repository.dart
Don't merge yet!  
I need to add github env variables for aws base api.
This PR switches to the newer AWS endpoint. 
Now the yearly summary comes as a separate PDF in email.
Also reverted the overview page to being state-less.
> fix: Bff 646 download yearly overview

- ios/Runner/Runner.entitlements
This will stop the warning email from Apple. "ITMS-90078: Missing Push Notification Entitlement "
We are now declaring the entitlement 🤠
> chore: Enable push notification capability

- lib/core/network/api_service.dart
- lib/utils/util.dart
- pubspec.lock
- pubspec.yaml
> Revert "feat: BFF-976 Added certificate pinning for backend"

- lib/core/network/api_service.dart
- lib/core/network/certificate_check_interceptor.dart
- lib/core/network/network.dart
- lib/core/network/token_interceptor.dart
> feat: bff 976/certificate pinning

- lib/utils/util.dart
- pubspec.lock
- pubspec.yaml
> fix: BFF-976 Added certificates list and package

- lib/app/injection/injection.dart
- lib/app/routes/app_router.dart
- lib/app/routes/route_utils.dart
- lib/core/enums/collect_group_type.dart
- lib/core/network/api_service.dart
- lib/features/give/bloc/organisation/organisation_bloc.dart
- lib/features/give/pages/organization_list_page.dart
- lib/features/recurring_donations/cancel/cubit/cancel_recurring_donation_cubit.dart
- lib/features/recurring_donations/cancel/cubit/cancel_recurring_donation_state.dart
- lib/features/recurring_donations/cancel/repositories/cancel_recurring_donation_repository.dart
- lib/features/recurring_donations/cancel/widgets/cancel_recurring_donation_confirmation_dialog.dart
- lib/features/recurring_donations/overview/cubit/recurring_donations_cubit.dart
- lib/features/recurring_donations/overview/cubit/recurring_donations_state.dart
- lib/features/recurring_donations/overview/models/recurring_donation.dart
- lib/features/recurring_donations/overview/pages/recurring_donations_overview_page.dart
- lib/features/recurring_donations/overview/repositories/recurring_donations_repository.dart
- lib/features/recurring_donations/overview/widgets/create_recurring_donation_button.dart
- lib/features/recurring_donations/overview/widgets/recurring_donation_item.dart
- lib/features/recurring_donations/overview/widgets/recurring_donations_list.dart
- lib/shared/models/collect_group.dart
- lib/shared/widgets/custom_navigation_drawer.dart
- lib/utils/util.dart
As a User I want to setup recurring donations.
> feat: bff 648 setup recurring donations

- lib/features/overview/widgets/givt_list_item.dart
Show local time of when the donation was executed instead of utc. Also show hour in 24 hour format instead of 12.
> BFF 1070 Fix time formatting of donation history

- lib/utils/util.dart
> Hotfix: BFF 990 Update certificate sha for production EU

- pubspec.yaml
> hotfix: Increase version number

- lib/features/recurring_donations/detail/models/recurring_donation_detail.dart
- lib/features/recurring_donations/detail/pages/recurring_donations_detail_page.dart
- lib/features/recurring_donations/detail/repository/detail_recurring_donation_repository.dart
When getting a list of previous recurring donation instances I get a list of {id, timestamp, amount}. This does not have the status and giftaid of that donation instance. So now I fetch all givts, select the ones that are the needed recurring instances and extract the status and giftaid.
> BFF 1085 Check the status&giftAid of recurring donations

- lib/features/recurring_donations/detail/cubit/detailed_recurring_donations_cubit.dart
- lib/features/recurring_donations/detail/cubit/detailed_recurring_donations_state.dart
- lib/features/recurring_donations/detail/pages/recurring_donations_detail_page.dart
When the user set up a recurring donation but no payment was deducted yet the detail view must display the upcoming instance.
> hotfix: When no recurring donation payment happened yet

- lib/features/registration/bloc/registration_bloc.dart
- lib/features/registration/pages/signup_page.dart
- lib/shared/widgets/custom_navigation_drawer.dart
Improve the loop, and make the family features accessible.
> hotfix: kids 918 register payment details

- lib/features/registration/bloc/registration_bloc.dart
> hotfix: Registration loop AND instead of OR

- lib/app/injection/injection.dart
- lib/app/routes/app_router.dart
- lib/core/network/country_iso_info.dart
- lib/features/first_use/pages/welcome_page.dart
Long press on the 'Let's go' button will create a user preference to set country to US. 
|  Initial |   Hacked |  Logged in  |
|    :----:   |    :----:   |          :---: |
| ![simulator_screenshot_AA92CB12-0DB2-4AA9-A819-9589F89A9486](https://github.com/givtnl/givt-app/assets/43034761/d3715996-7ee8-4514-bee0-64badf079ed6)       | ![simulator_screenshot_E0F941FE-80FB-419C-A5BA-DDC6A6497089](https://github.com/givtnl/givt-app/assets/43034761/7586a706-db07-436b-b7c3-98c117fb2b60)  |![simulator_screenshot_5AE7DF21-FA2A-4024-8F94-19B903C83F1C](https://github.com/givtnl/givt-app/assets/43034761/9a010754-38b7-4201-9a42-427e5ff201b5)   |
> feature: KIDS 1190 Hack for USA

- lib/core/network/api_service.dart
> hotfix: Use the env variable for base url

- lib/core/network/api_service.dart
- lib/features/first_use/pages/welcome_page.dart
- lib/features/registration/cubit/stripe_cubit.dart
- lib/features/registration/pages/signup_page.dart
> hotfix: Fix hack for usa

- lib/features/registration/pages/personal_info_page.dart
- lib/features/registration/widgets/mobile_number_form_field.dart
> feat: KIDS 1198 limit to 10 digits

- lib/app/app.dart
- lib/features/first_use/pages/welcome_page.dart
- lib/features/give/widgets/context_list_tile.dart
Made some small UI changes to support smaller screens + on android the top bar is transparent now :-)
> UI improvements

- lib/core/network/certificate_check_interceptor.dart
> fix: BFF-1136 Skip certificate check when user is offline

- lib/shared/widgets/custom_navigation_drawer.dart
Hide family options for current US users since functionality is not fully implemented.
> KIDS 1241 Hide family item

- lib/features/account_details/pages/change_phone_number_bottom_sheet.dart
- lib/utils/util.dart
> fix: BFF-1069 Added prefixes to regEx

- lib/features/overview/pages/overview_page.dart
> fix: BFF-1093 Added backbutton for appbar

- lib/features/amount_presets/widgets/preset_form_field.dart
- lib/shared/pages/fingerprint_bottom_sheet.dart
> feat: bff 1089/presets

- lib/features/children/overview/cubit/children_overview_cubit.dart
- lib/features/children/overview/models/profile.dart
> hotfix: KIDS 1235 Revert to shared prefs

- pubspec.yaml
> fix: Updated to version 4.0.0

- packages/http_certificate_pinning/CHANGELOG.md
> fix: Deleted previous change logs

- pubspec.yaml
> fix: Updated to 4.0.1

- lib/app/app.dart
- lib/features/give/pages/select_giving_way_page.dart
- lib/features/give/widgets/context_list_tile.dart
- lib/shared/widgets/about_givt_bottom_sheet.dart
> BFF-1204 - If you are using the bigger text on the iPhone, text are cut and screens are not showing really well

- android/app/src/main/res/values/styles.xml
- pubspec.yaml
> Remove black bar

- lib/app/bootstrap.dart
- lib/core/logging/log_message.dart
- lib/core/logging/logging_service.dart
- lib/features/auth/repositories/auth_repository.dart
> fix: Added device id for the logs and added boolean for migration

- lib/features/auth/pages/login_page.dart
- lib/shared/widgets/custom_text_form_field.dart
> add autofill

- lib/app/bootstrap.dart
> remove empty logging

- lib/features/auth/repositories/auth_repository.dart
> fix: bff 1201/user ext

- lib/features/children/create_child/pages/create_child_page.dart
The date of birth selection for the create child profile feature is switched to the native flutter date picker
> Children DOB selection is switched to the native flutter date picker

- lib/features/first_use/pages/welcome_page.dart
> fix: Removed changes from previous commit as it's possible again

- lib/features/give/bloc/organisation/organisation_bloc.dart
- lib/features/give/pages/home_page.dart
- lib/features/give/widgets/choose_amount.dart
- lib/features/give/widgets/collection_form_field.dart
- lib/features/give/widgets/numeric_keyboard.dart
> fix: bff 1224/home screen

- lib/core/enums/collect_group_type.dart
- lib/features/give/bloc/organisation/organisation_bloc.dart
- lib/features/give/bloc/organisation/organisation_state.dart
- lib/features/give/pages/home_page.dart
- lib/features/give/pages/organization_list_page.dart
- lib/features/give/widgets/choose_amount.dart
- lib/features/give/widgets/choose_category.dart
- lib/features/give/widgets/collection_form_field.dart
- lib/features/give/widgets/numeric_keyboard.dart
- lib/shared/models/collect_group.dart
> fix: Bff 1226/search organisation

- .github/workflows/main.yaml
> fix: Disabled spellcheck

- lib/features/first_use/pages/welcome_page.dart
- lib/features/give/pages/home_page.dart
- lib/features/give/widgets/numeric_keyboard.dart
- lib/shared/dialogs/faq_bottom_sheet.dart
- lib/shared/widgets/about_givt_bottom_sheet.dart
- lib/shared/widgets/bottom_sheet_layout.dart
- lib/shared/widgets/custom_navigation_drawer.dart
- pubspec.lock
> fix: bff 1214/bottom sheet

- pubspec.yaml
- [] 🛠️ Bug fix (non-breaking change which fixes an issue)
> chore: Version bump

- lib/features/give/bloc/organisation/organisation_bloc.dart
- pubspec.lock
- pubspec.yaml
> fix: BFF-1232 Remove diatritics when searching

- lib/app/routes/app_router.dart
- lib/features/give/bloc/organisation/organisation_bloc.dart
- lib/features/give/bloc/organisation/organisation_event.dart
> fix: Use collectgroup type index instead of -1

- lib/features/auth/cubit/auth_cubit.dart
- lib/features/auth/cubit/auth_state.dart
- lib/features/auth/pages/email_signup_page.dart
- lib/features/auth/pages/login_page.dart
> fix: BFF-1239 Added no internet state for auth cubit

- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- lib/features/give/pages/home_page.dart
- lib/shared/widgets/custom_navigation_drawer.dart
- lib/utils/app_theme.dart
- packages/flutter_device_region/ios/Classes/SwiftDeviceRegionPlugin.swift
- pubspec.lock
- pubspec.yaml
> Multiple fixes

- lib/features/give/bloc/give/give_bloc.dart
- lib/features/give/bloc/give/give_state.dart
- lib/features/give/pages/select_giving_way_page.dart
> fix: BFF-1288 Added 30 sec span giving popup and error

- lib/core/logging/logging_service.dart
- pubspec.lock
- pubspec.yaml
> fix: BFF-1293 Added iphone model

- pubspec.yaml
> Updated to version 4.0.6

- android/app/src/main/AndroidManifest.xml
- lib/features/give/pages/bt_scan_page.dart
- pubspec.lock
- pubspec.yaml
> Fix: Improve beacon search on Android

- lib/features/give/bloc/give/give_bloc.dart
- lib/features/recurring_donations/create/cubit/create_recurring_donation_cubit.dart
- lib/features/recurring_donations/create/widgets/create_recurring_donation_bottom_sheet.dart
- lib/features/recurring_donations/overview/widgets/recurring_donation_item.dart
> fix: bff 1041/recurring fixes

- lib/features/give/pages/gps_scan_page.dart
> fix: BFF-1240 Ask for location if not permitted

- lib/features/give/pages/bt_scan_page.dart
- lib/shared/dialogs/faq_bottom_sheet.dart
> fix: BFF-1306 Added missing faqs

- lib/app/routes/app_router.dart
- lib/shared/pages/fingerprint_bottom_sheet.dart
> fix: Show last organization donated to

- lib/features/auth/widgets/terms_and_conditions_dialog.dart
- lib/features/registration/bloc/registration_bloc.dart
- lib/features/registration/pages/bacs_explanation_page.dart
- lib/features/registration/pages/personal_info_page.dart
- lib/features/registration/pages/signup_page.dart
- lib/utils/auth_utils.dart
> fix: BFF-1300 When the country is US add the default strings

- lib/features/auth/repositories/auth_repository.dart
> fix: BFF-1329 Fetch user extenstion during start up

- lib/l10n/arb/app_de.arb
- lib/l10n/arb/app_en.arb
- lib/l10n/arb/app_en_US.arb
- lib/l10n/arb/app_nl.arb
> chore:Po editor

- lib/features/personal_summary/add_external_donation/cubit/add_external_donation_cubit.dart
- lib/features/personal_summary/add_external_donation/models/external_donation.dart
- lib/features/personal_summary/add_external_donation/pages/add_external_donation_page.dart
- lib/features/personal_summary/add_external_donation/widgets/add_edit_external_donation_form.dart
- lib/features/personal_summary/overview/bloc/personal_summary_bloc.dart
- lib/features/personal_summary/overview/bloc/personal_summary_state.dart
- lib/features/personal_summary/overview/pages/personal_summary_page.dart
> fix: BFF-1339 Fetch the external donations after addition. Allow users to add external donations to previous months

- lib/app/routes/app_router.dart
- lib/features/auth/cubit/auth_state.dart
- lib/features/auth/pages/email_signup_page.dart
- lib/features/give/bloc/organisation/organisation_bloc.dart
- lib/features/give/bloc/organisation/organisation_event.dart
- lib/features/give/pages/home_page.dart
- lib/features/recurring_donations/create/widgets/create_recurring_donation_bottom_sheet.dart
> fix: BFF-1329 Do not check for sim card only on register and terms dialog. Added Debug panel

- pubspec.yaml
> chore: Updated to v4.0.7

- pubspec.yaml
> chore: Update to v4.0.8

- lib/features/auth/repositories/auth_repository.dart
> fix: BFF-1357 Clear local cache when user terminates account

- lib/features/auth/cubit/auth_cubit.dart
> fix: BFF-1359 Clear cache when user is trying to register a different email

- lib/app/injection/injection.dart
- lib/features/account_details/bloc/personal_info_edit_bloc.dart
- lib/features/amount_presets/models/amount_presets.dart
- lib/features/amount_presets/models/models.dart
- lib/features/amount_presets/models/user_presets.dart
- lib/features/auth/repositories/auth_repository.dart
- lib/shared/models/user_ext.dart
- lib/shared/pages/change_max_amount_bottom_sheet.dart
- lib/shared/pages/fingerprint_bottom_sheet.dart
> fix: BFF-1372 Added url check for country if it's available on the device

- lib/features/amount_presets/pages/amount_presets_page_view.dart
- lib/features/give/widgets/choose_amount.dart
- lib/features/give/widgets/numeric_keyboard.dart
- lib/features/recurring_donations/overview/widgets/recurring_donation_item.dart
- lib/utils/util.dart
> BFF 1194 - As UK and US user you should see a . instead of ,

- lib/app/app.dart
- lib/features/auth/repositories/auth_repository.dart
If data is already removed on logout, just accept it
+ improvement on language
> BFF-1375 - If data is already removed on logout, just accept it + language fix

- lib/core/auth/local_auth_info.dart
- lib/features/auth/cubit/auth_cubit.dart
> fix: BFF-1375 Refresh the user extenstion stored in the state

- lib/features/auth/cubit/auth_cubit.dart
- lib/shared/models/user_ext.dart
> chore: BFF-1376 Added logging for logging in and out for userExt

- pubspec.yaml
> chore: Update to v4.0.9

- lib/app/app.dart
- lib/app/injection/injection.dart
- lib/core/enums/country.dart
- lib/features/auth/cubit/auth_cubit.dart
- lib/features/auth/pages/email_signup_page.dart
- lib/features/auth/pages/login_page.dart
- lib/features/auth/repositories/auth_repository.dart
- lib/features/auth/widgets/terms_and_conditions_dialog.dart
- lib/features/first_use/pages/welcome_page.dart
- lib/features/give/widgets/choose_amount.dart
- lib/utils/country_emoji.dart
- lib/utils/utils.dart
> feat: BFF-1396 as a user i need to be able to select a country on login

- lib/core/enums/country.dart
- lib/core/network/token_interceptor.dart
- lib/features/auth/cubit/auth_cubit.dart
- lib/shared/pages/change_max_amount_bottom_sheet.dart
> fix: BFF-1375 Fixed issue where the user extension was empty while login without internet

- lib/features/registration/pages/personal_info_page.dart
> BFF-1398 - UK and US users cant finish their registration

- lib/features/registration/pages/credit_card_details_page.dart
- lib/shared/widgets/custom_navigation_drawer.dart
> fix: BFF-1398 Go to give page when cancelled

- lib/features/first_use/pages/welcome_page.dart
- lib/shared/dialogs/warning_dialog.dart
- lib/shared/widgets/custom_navigation_drawer.dart
> fix: BFF-1406 Prevent user to logout and login when he's offline

- lib/shared/repositories/givt_repository.dart
…at prevents them from processing
> fix: BFF-1395 Remove offline givts if there is an error from the server

- pubspec.yaml
> chore: Updated to v4.0.10

- lib/features/give/pages/bt_scan_page.dart
- pubspec.lock
- pubspec.yaml
> fix: BFF-1370 bluetooth donation fix

- android/app/src/main/res/values/styles.xml
- pubspec.lock
- pubspec.yaml
We need to use Appcompat styling for older Android versions
> BFF-1351 - Fingerprint login doesnt work on Android 8

- lib/app/routes/app_router.dart
> fix: BFF-1378 Fixed issue when navigating from the kerkedienstgemist app

- lib/features/children/details/cubit/child_details_cubit.dart
- lib/features/children/details/pages/child_details_page.dart
Infinite loading on child details page is fixed
> Infinite loading on child details page is fixed

- lib/features/give/bloc/give/give_bloc.dart
- lib/features/give/pages/select_giving_way_page.dart
> fix: BFF-1393 Display multiple possible actions on the dialog when a inactive qr-code is scanned 

- pubspec.yaml
> chore: Updated to v4.0.11

- lib/features/auth/pages/login_page.dart
> feat: BFF-1414 Improved login page

- lib/features/children/family_history/family_history_cubit/family_history_cubit.dart
> Bug fix: kids 1054 family history - float pending donations to top

- lib/features/children/family_history/family_history_cubit/family_history_cubit.dart
- lib/features/children/overview/pages/children_overview_page.dart
Forgot to remember allowances when fetching more history items. This fixes it.
Also fix the '+ Add child' button spacing
> Bug fix: previously loaded allowances

- lib/features/give/pages/bt_scan_page.dart
- pubspec.yaml
- [] 🛠️ Bug fix (non-breaking change which fixes an issue)
> Bluetooth optimisations (KIDS-1419)

- lib/features/personal_summary/overview/bloc/personal_summary_state.dart
- lib/features/personal_summary/overview/widgets/monthly_past_twelve_months_card.dart
> Annual summary overview (BFF-645)

- lib/features/registration/pages/personal_info_page.dart
- lib/features/registration/widgets/payment_system_form_field.dart
After a UK user registered through the SEPA flow and the payment provider is only processing BACS. We decided to have the flows based on the country selected
> BFF-1420 Display the SEPA or BACS flow based on the country selected

- lib/features/personal_summary/overview/models/giving_goal.dart
- lib/features/personal_summary/overview/widgets/monthly_giving_goal_progress.dart
When the giving goal is annual make sure you display the monthly remaining giving goal
> BFF-1425 If periodicity is annually make sure that you display monthly remaining goal

- lib/features/personal_summary/overview/bloc/personal_summary_bloc.dart
- lib/features/personal_summary/overview/bloc/personal_summary_state.dart
- lib/features/personal_summary/overview/widgets/annual_bar_chart.dart
- lib/features/personal_summary/overview/widgets/annual_summary_card.dart
- lib/features/personal_summary/yearly_overview/cubit/yearly_overview_state.dart
- lib/features/personal_summary/yearly_overview/widgets/giving_goal_summary_card.dart
- lib/features/personal_summary/yearly_overview/widgets/monthly_summary_card.dart
We should avoid making calculations for previous year if the user is new or didn't donate to previous year
> BFF-645 Fixed issue where the issue didn't give previous year

- lib/features/give/pages/select_giving_way_page.dart
Redirect user to the selecting giving page
> BFF-1427 Redirect to the select giving way page

- android/app/src/main/AndroidManifest.xml
- lib/app/app.dart
- lib/app/bootstrap.dart
- lib/app/injection/injection.dart
- lib/core/notification/notification_service.dart
- lib/features/give/pages/home_page.dart
- lib/features/personal_summary/overview/widgets/annual_bar_chart.dart
- lib/features/personal_summary/overview/widgets/monthly_giving_goal_progress.dart
- pubspec.lock
- pubspec.yaml
This pr contains the monthly notifications and yearly notifications scheduled locally
> Monthly notifications (BFF-657)

- lib/app/app.dart
- lib/app/routes/app_router.dart
- pubspec.lock
- pubspec.yaml
This removes the badge on Startup + I updated to go_router package (including breaking changes)
> Removing the badge for iOS users migrated from Native App (BFF-1410)

- lib/app/app.dart
Allow up to 1.2 as fontsize when people have changed the size on their phone.
> Allow bigger fontsize when set in accessibility (BFF-1452) 

- lib/features/give/bloc/organisation/organisation_bloc.dart
> Search filter is showing orgs from other category (BFF-1407)

- lib/core/notification/notification_service.dart
- lib/features/give/pages/home_page.dart
Enable yearly notifications + Localization
> Enable yearly notifications + Localization (BFF-656)

- lib/features/give/pages/bt_scan_page.dart
restart scan process after timeout + make sure that we stop processing scan results on manual flow
> Beacon improvements (BFF-1454)

- lib/core/network/api_service.dart
- lib/features/children/create_child/models/child.dart
- Create child feature switched to bff endpoint
> Task: kids-1330: create child feature switched to bff endpoint

- lib/app/firebase_options.dart
- lib/app/firebase_options_dev.dart
> Firebase config fixes

- .github/release-drafter.yml
- lib/features/auth/cubit/auth_cubit.dart
- lib/shared/models/user_ext.dart
- pubspec.lock
- pubspec.yaml
> Fix last version v4.0.13

- lib/features/give/bloc/give/give_bloc.dart
Added check as there are errors in logit with null value for qr-code
> BFF-1462 Added check for null value for QR code

- lib/features/give/pages/organization_list_page.dart
The issue was that the token was always expired. Therefore we have to ask the user to login
> BFF-1447 Check if the token is expired, if so ask user to login

- lib/features/give/pages/giving_page.dart
> BFF-1377 Do not display the instance Name if it's the same as orgName

- lib/app/routes/app_router.dart
- lib/core/notification/notification_service.dart
- lib/features/recurring_donations/overview/pages/recurring_donations_overview_page.dart
When you receive a notification you should be redirected to the screen accordingly. Therefore, I am uisng the routeDelegate to do so.
> BFF-1459 Navigate to the the payload screen

- lib/features/give/pages/gps_scan_page.dart
Adjusted location search and increased timeLimit
> BFF-1380 Adjusted location search

- lib/features/account_details/pages/personal_info_edit_page.dart
> Feature: Hide US fake home address

- android/app/build.gradle
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- lib/features/auth/cubit/auth_cubit.dart
- lib/features/registration/bloc/registration_bloc.dart
- pubspec.lock
- pubspec.yaml
> Fix: Android 6 + 7 are crashing on startup

- lib/core/notification/notification_service.dart
> BFF-1459 Added changed payload to scheduled notifications

- lib/app/routes/app_router.dart
- lib/app/routes/pages.dart
- lib/features/give/pages/home_page.dart
- lib/shared/widgets/loading_page.dart
- lib/shared/widgets/splash_screen.dart
- lib/shared/widgets/widgets.dart
- pubspec.lock
- pubspec.yaml
By using the path from the enum "Pages" we can open the app using an external link as the one provided below
https://givtapp.net/download?page=personal-summary
The implementation is meant to use the query parameter "page" to navigate to a named route dynamically
> BFF-1471 Open app from external link to a certain page using the path

- lib/features/recurring_donations/detail/pages/recurring_donations_detail_page.dart
Use the recurring donation starting date if there is no donation present in this recurring donation. The previous code was always setting the next iteration of the "nextTime" variable
> BFF-1352 Always use the recurring donation start date

- lib/features/registration/pages/signup_page.dart
> BFF-1433 Added scrollchildview to scroll form

- lib/features/give/pages/organization_list_page.dart
- lib/shared/widgets/about_givt_bottom_sheet.dart
Allow users to report a missing organization from the list
> BFF-1196 Added report missing organization to the list

- lib/features/give/pages/giving_page.dart
> BFF-1431 Pop empty page when the browser has been opened

- lib/shared/widgets/about_givt_bottom_sheet.dart
> BFF-1479 Removed set state on change

- lib/core/notification/notification_service.dart
> Improvement: Add notification case DonationApproval with page redirection

- lib/app/injection/injection.dart
- lib/core/network/api_service.dart
- lib/core/network/certificate_check_interceptor.dart
- lib/core/network/network_info.dart
- lib/core/network/token_interceptor.dart
- lib/features/first_use/pages/welcome_page.dart
- lib/features/give/pages/giving_page.dart
- lib/shared/widgets/custom_navigation_drawer.dart
- lib/utils/app_theme.dart
- packages/http_certificate_pinning/pubspec.yaml
- pubspec.lock
- pubspec.yaml
Solves the following: 
1. Reseting the collections fields
2. Internet checker connection check
3. Disabled the material 3 by default
> BFF-1455 Updated internet checker plus dependencies as well as http

- lib/app/bootstrap.dart
- lib/core/notification/notification_service.dart
> BFF-1487 Background notifications

- lib/features/give/bloc/organisation/organisation_bloc.dart
> BFF-1489 Changed the index of last selected org

- lib/app/bootstrap.dart
- lib/app/routes/app_router.dart
- lib/core/notification/notification_service.dart
Because the init method is always called whenever the app is launched.
> BFF-1487 Redirect notification

- lib/features/overview/pages/overview_page.dart
> BFF-1490 Overlay null issue check

- lib/features/overview/pages/overview_page.dart
- lib/features/overview/widgets/feature_overlay.dart
> Make it possible to click everywhere on overlay donation history

- lib/features/account_details/pages/personal_info_edit_page.dart
- lib/shared/models/user_ext.dart
- AccountBrand filed added to the UserExt model; 
- AccountBrand + AccountNumber is showing on Personal Info screen for US users
> Feature:KIDS-43 show payment info for US users

- lib/features/amount_presets/widgets/preset_form_field.dart
- lib/features/personal_summary/giving_goal/pages/setup_giving_goal_bottom_sheet.dart
- lib/features/personal_summary/overview/widgets/monthly_past_twelve_months_card.dart
- lib/features/personal_summary/overview/widgets/narrow_card.dart
I changed the implementation to use the monthly giving goal instead of the giving amount
> BFF-1468 Monthly giving amount instead of giving amount

- lib/features/overview/widgets/feature_overlay.dart
> BFF-1492 Adjusted feature overlay position

- lib/features/give/bloc/give/give_bloc.dart
- lib/features/give/bloc/give/give_event.dart
- pubspec.lock
- pubspec.yaml
Upgrade package to latest version which should resolve some errors we get in our logging
> Update FBP package

- lib/app/routes/app_router.dart
- lib/shared/widgets/custom_navigation_drawer.dart
- lib/utils/auth_utils.dart
> BFF-1485 Do not redirect the user to the home page if he's already there

- lib/features/registration/bloc/registration_bloc.dart
> Feature: After US registration fill in user session

- lib/features/registration/bloc/registration_bloc.dart
> feature: Refresh session after EU registration

- lib/features/children/parental_approval/dialogs/parental_approval_dialog.dart
- lib/features/children/parental_approval/widgets/parental_approval_confirmation_page.dart
- lib/features/children/parental_approval/widgets/parental_approval_loading_page.dart
Removing the box height allows the content to grow or shrink vertically. 
Changed some sizing to make it closer to design.
> Improvement: KIDS-160 Replace box height with padded limit

- lib/features/overview/widgets/feature_overlay.dart
- lib/features/overview/widgets/inverted_clipper.dart
Tested on following screen sizes:
1. 4.0
2. 4.7
3. 5.5
4. 6.7
> BFF-1492 Adjusted overlay text and circle

- lib/features/give/pages/home_page.dart
- lib/shared/bloc/infra/infra_cubit.dart
- lib/shared/models/app_update.dart
- lib/shared/repositories/infra_repository.dart
1. Added deviceOS parameter
2. Changed names fromJson
> BFF-1468 update dialog

- lib/features/give/pages/home_page.dart
- lib/features/registration/pages/credit_card_details_page.dart
- lib/features/registration/pages/personal_info_page.dart
- lib/features/registration/pages/signup_page.dart
- lib/l10n/arb/app_de.arb
- lib/l10n/arb/app_en.arb
- lib/l10n/arb/app_en_US.arb
- lib/l10n/arb/app_nl.arb
- lib/utils/util.dart
- Add title for sign up page
- Remove email field on sign up page
- Remove personal info page (Mobile and country input) 
- Update US dialog strings
- Stripe success dialog redirects to family page
> Feature: Kids-178 Simplify US registration Flow

- lib/app/app.dart
- lib/features/give/widgets/choose_amount.dart
- lib/features/personal_summary/overview/widgets/annual_bar_chart.dart
- lib/features/recurring_donations/create/widgets/create_recurring_donation_bottom_sheet.dart
Display period based on the country of the user
> BFF-1350 Adjusted decimal amount in dialogs

- lib/features/recurring_donations/cancel/widgets/cancel_recurring_donation_confirmation_dialog.dart
- lib/shared/dialogs/givt_dialog.dart
- lib/shared/widgets/donation_type_sheet.dart
Localized the popup strings
The native dialogs, I can't localize from the Flutter side as they use the Info.plist strings and those are needed for the package/plugin that is asking for permissions.
> BFF-1154 Localized popup strings

- lib/features/give/widgets/add_colletion_button.dart
- lib/features/give/widgets/choose_amount.dart
- lib/features/give/widgets/collection_form_field.dart
- lib/features/give/widgets/widgets.dart
> BFF-957 Changed add collection button color and refactor widgets

- lib/features/give/widgets/filter_suggestion_card.dart
Increased the size of the text on the card from discover page
> BFF-968 Made discover page text bigger

- ios/Gemfile
https://github.com/fastlane/fastlane/issues/21762 - when fastlane closes this issue we should remove the gemfile again
> temp hotfix for pipeline

- lib/features/give/widgets/choose_amount.dart
> BFF-1499 Readded collection name after refactoring

- lib/core/auth/local_auth_info.dart
1. Catch PlatformException when user locks out after biometrics auth failure
2. Return false in that case
> BFF-1501 Catch PlatformException

- lib/features/registration/pages/signup_page.dart
Signup screen is reimplemented to enable scroll
> Bug: kids-174: Signup screen is reimplemented to enable scroll

- lib/features/give/pages/organization_list_page.dart
- lib/features/give/widgets/choose_category.dart
- lib/features/give/widgets/discover_suggestion_card.dart
- lib/features/give/widgets/filter_suggestion_card.dart
- lib/features/give/widgets/widgets.dart
I splitted up the card as they a different in multiple ways (text didn't fit anymore and wasn't always aligned everywhere)
> Refactor category selection cards

- lib/features/children/add_member/cubit/add_member_cubit.dart
- lib/features/children/add_member/pages/add_member_form_page.dart
> fix deletion

- lib/features/children/add_member/pages/add_member_form_page.dart
- pubspec.yaml
> Improve bottom buttons family creation

- lib/features/children/add_member/pages/add_member_form_page.dart
- pubspec.yaml
Quick fix for the Create Family Page
> Release v4.1.1

- lib/features/give/pages/home_page.dart
- Added red dot to scaffold drawer
> BFF-858 Add badge to show registration and mandate status in app bar

- lib/features/overview/pages/overview_page.dart
- lib/features/overview/widgets/givt_list_item.dart
- lib/shared/widgets/custom_navigation_drawer.dart
- lib/shared/widgets/drawer_menu_item.dart
- lib/shared/widgets/summary_menu_item.dart
- lib/shared/widgets/widgets.dart
1. Adjusted dimensions on 4 inch device of the Givt List item 
2. Removed "build" methods from navigation drawer and created separate widget
> BFF-1497 Donation history list item

- lib/features/give/pages/giving_page.dart
Temporary solution to allow user to go back to the home screen
> BFF-1431 Added go back home button

- lib/features/recurring_donations/detail/pages/recurring_donations_detail_page.dart
- lib/features/recurring_donations/detail/widgets/detail_list_item.dart
Added GiftAid icon to recurring donations overview
> BFF-1132 Added GiftAid icon to recurring donation

- lib/features/personal_summary/overview/dialogs/first_use_summary_dialog.dart
1. Added animated indexes at the bottom of the popup
> BFF-1011 Added animated indexes

- lib/features/children/add_member/pages/add_member_form_page.dart
- lib/features/children/add_member/widgets/add_member_form.dart
- lib/features/children/add_member/widgets/family_text_form_field.dart
- scroll down and focus name field when new member form added
> Improvement:kids-246 scroll down and focus new member form

- lib/features/children/add_member/widgets/add_member_form.dart
Add timer that quickly increases/decreases the _allowanceCounter when button is held down
> Improvement: Kids-239 Replace Icon button with Gesture Detector

- lib/features/children/add_member/widgets/add_member_form.dart
> Hotfix: Merge conflict issue is fixed 

- lib/features/children/add_member/widgets/add_member_form.dart
- lib/features/children/overview/pages/family_overview_page.dart
> Fix: no children redirection

- lib/features/children/add_member/widgets/add_member_form.dart
- lib/features/registration/pages/signup_page.dart
> Improvement: kids-252 capitalize keyboard for name input

- lib/features/children/add_member/widgets/add_member_form.dart
- lib/features/children/add_member/widgets/family_text_form_field.dart
- lib/utils/color_schemes.g.dart
Mathematically vertically align the text form fields. 
Change trash-icon color to error color. 
update the error color to error50
> Improvement: kids 250 add member form improvements

- lib/features/children/add_member/widgets/add_member_form.dart
Focus issue when Child/Parent tab is switched is fixed
> Bug: kids-246 Focus issue when Child/Parent tab is switched is fixed

- lib/features/give/pages/organization_list_page.dart
- Moved report missing org to the bottom of the list
> BFF-1502 Moved report missing org to the bottom of the list

- lib/features/children/add_member/pages/add_member_form_page.dart
- lib/features/children/add_member/widgets/add_member_form.dart
- lib/utils/app_theme.dart
- pubspec.lock
- pubspec.yaml
Done button is added to the child's age field numeric keyboard
> Improvement:kids-253 Done button is added to the child's age field numeric keyboard

- lib/features/children/add_member/widgets/family_text_form_field.dart
> Improvemen: kids-250 align the hintext and labeltext

- lib/features/overview/bloc/givt_bloc.dart
> Yearly Overview bug (KIDS-283)

- lib/features/children/add_member/pages/add_member_form_page.dart
- lib/features/registration/pages/signup_page.dart
- lib/l10n/arb/app_de.arb
- lib/l10n/arb/app_en.arb
- lib/l10n/arb/app_en_US.arb
- lib/l10n/arb/app_nl.arb
> Improvement: kids-255 add text to loading state

- lib/features/children/add_member/repository/add_member_repository.dart
- lib/features/children/add_member/widgets/add_member_form.dart
> hotfix renaming

- lib/features/children/add_member/pages/add_member_form_page.dart
> Kids-256 Border is kept within the padding

- lib/l10n/arb/app_de.arb
- lib/l10n/arb/app_en.arb
- lib/l10n/arb/app_en_US.arb
- lib/l10n/arb/app_nl.arb
> Po editor update

- android/app/src/main/AndroidManifest.xml
- ios/Runner/Info.plist
- lib/features/children/overview/pages/family_overview_page.dart
- lib/features/children/overview/widgets/download_givt_for_kids_app_widget.dart
- lib/l10n/arb/app_de.arb
- lib/l10n/arb/app_en.arb
- lib/l10n/arb/app_en_US.arb
- lib/l10n/arb/app_nl.arb
- pubspec.lock
- pubspec.yaml
- Add download g4k floating action button to the family overview page
> Feature: kids-305 add download g4k banner to the family overview page

- pubspec.yaml
> Version increase

- lib/features/children/parental_approval/widgets/parental_approval_dialog_content.dart
The tappable area for the X button in approval dialog is increased
> improvement: The tappable area for the X button in approval dialog is increased

- lib/app/injection/injection.dart
- lib/core/network/api_service.dart
- lib/features/children/avatars/cubit/avatars_cubit.dart
- lib/features/children/avatars/cubit/avatars_state.dart
- lib/features/children/avatars/models/avatar.dart
- lib/features/children/avatars/repositories/avatars_repository.dart
- Fetching avatars feature is draftly implemented (model,cubit,repo,apiservice) but not tested since the endpoint is not ready yet
> Feature:kids-320 Fetching avatars feature is implemented (draftly)

- lib/app/injection/injection.dart
- lib/app/routes/app_router.dart
- lib/app/routes/pages.dart
- lib/core/network/api_service.dart
- lib/features/account_details/pages/personal_info_edit_page.dart
- lib/features/children/avatars/models/avatar.dart
- lib/features/children/avatars/repositories/avatars_repository.dart
- lib/features/children/avatars/screens/avatar_selection_screen.dart
- lib/features/children/avatars/widgets/avatar_item.dart
- lib/features/children/edit_profile/cubit/edit_profile_cubit.dart
- lib/features/children/edit_profile/cubit/edit_profile_state.dart
- lib/features/children/edit_profile/models/edit_profile.dart
- lib/features/children/edit_profile/repositories/edit_profile_repository.dart
- lib/shared/models/user_ext.dart
- lib/shared/widgets/custom_green_elevated_button.dart
- lib/shared/widgets/parent_avatar.dart
- fetch avatars feature/screen implemented; 
- Personal info screen redesigned; 
- Edit avatar feature is implemented;
> Feature:kids-286 fetch and edit avatars 

- lib/core/enums/amplitude_events.dart
- lib/features/children/avatars/screens/avatar_selection_screen.dart
- lib/features/children/avatars/widgets/avatar_item.dart
- lib/features/children/parental_approval/widgets/parental_approval_dialog_content.dart
- lib/shared/widgets/parent_avatar.dart
> Task: kids-381: Amplitude is added for edit avatars

- lib/core/enums/amplitude_events.dart
- lib/features/children/avatars/screens/avatar_selection_screen.dart
- lib/features/children/avatars/widgets/avatar_item.dart
- lib/features/children/parental_approval/widgets/parental_approval_dialog_content.dart
- lib/shared/widgets/parent_avatar.dart
- pubspec.yaml
> Release to production

- pubspec.lock
- pubspec.yaml
> update package of mobile qr code scanner

- lib/app/routes/app_router.dart
- lib/features/account_details/pages/personal_info_edit_page.dart
- lib/features/children/edit_child/pages/edit_child_page.dart
- lib/features/children/overview/cubit/family_overview_cubit.dart
- lib/features/children/overview/widgets/profile_overview_tile.dart
- lib/features/children/parental_approval/widgets/parental_approval_dialog_content.dart
- Fix navigating back from updating profile picture to refresh the family profiles
> Feature: kids 354 family tiles update

- lib/features/children/overview/widgets/profile_overview_tile.dart
> bug kids-400 same name parent and child

- .github/workflows/android.yml
> Automatic release to production for Android

- pubspec.yaml
> Prod release (KIDS-329)

- lib/features/children/family_history/family_history_cubit/family_history_cubit.dart
- lib/features/children/family_history/repository/family_history_repository.dart
-The sorting logic was removed from FE side
> Bug: kids-350 donation history logic reimplemented (simplified)

- lib/features/children/add_member/widgets/vpc_page.dart
- Don't track vpcAccepted in case of no funds for vpc
> Bug:kids-456 vpc amplitude tracking fix

- lib/features/children/cached_members/dialogs/cached_members_dialog.dart
- Dialog layout fixed by making background size bigger
> Bug:kids-455 VPC no funds dialog's layout fix

- lib/features/children/add_member/cubit/add_member_cubit.dart
- lib/features/children/add_member/widgets/vpc_page.dart
- Send vpcAccepted only if members were created
> Bug:kids-456 vpcAccepted event tracking fix 

- lib/features/auth/cubit/auth_cubit.dart
> Improvements on updating notification id

- lib/features/children/family_history/family_history.dart
- lib/features/children/overview/widgets/family_available_page.dart
> KIds-467 Fix history scroll controller

- .github/workflows/main.yaml
- android/app/src/main/AndroidManifest.xml
- lib/app/bootstrap.dart
- lib/core/notification/notification_service.dart
- lib/features/give/pages/home_page.dart
> Notifications

- lib/features/children/details/models/profile_ext.dart
- lib/features/children/edit_child/pages/edit_child_page.dart
> Disable edit allowance if pending

- lib/core/network/certificate_check_interceptor.dart
> Release to production: Remove certificate pinning

- lib/features/children/family_goal_tracker/model/family_goal.dart
- lib/features/children/family_goal_tracker/widgets/goal_active_widget.dart
- lib/features/children/family_goal_tracker/widgets/gradient_progress_bar.dart
- lib/utils/app_theme.dart
> Add non-approved donations to progressbar (KIDS-521)

- .github/workflows/android.yml
- .github/workflows/ios.yml
- .github/workflows/main.yaml
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- pubspec.lock
- pubspec.yaml
> Update dependencies and flutter version

- android/app/build.gradle
> Release fix: Update minSdkVersion to 24

- lib/features/children/family_history/family_history_cubit/family_history_cubit.dart
- lib/features/children/family_history/widgets/pending_donation_widget.dart
- lib/features/children/parental_approval/widgets/parental_approval_dialog_content.dart
> improvement to refreshing part of family overview after decline/approval

- lib/features/children/family_goal_tracker/widgets/gradient_progress_bar.dart
Make g4k and givt gradient bar look the same: starter circle, and white shadow.
> add starter circle and white shadow

- lib/features/children/family_goal_tracker/widgets/goal_active_widget.dart
> Wrap progress bar with builder

- pubspec.lock
- pubspec.yaml
> Revert packages

- lib/features/children/family_goal_tracker/widgets/goal_active_widget.dart
- lib/features/children/family_goal_tracker/widgets/goal_completed_widget.dart
- pubspec.yaml
No version increase needed since apps have not been submitted yet
> Release to production: fix long organisation name

- android/app/build.gradle
- android/build.gradle
- android/gradle.properties
- android/settings.gradle
- pubspec.lock
- pubspec.yaml
> Use latest kotlin version + updated build gradle to latest format

- .github/workflows/release-drafter.yml
- lib/core/network/certificate_check_interceptor.dart
- lib/features/auth/cubit/auth_cubit.dart
> Enable for iOS + First clear prefs and then refetch certs

- lib/features/children/family_history/models/child_donation.dart
- lib/features/children/family_history/widgets/actioned_donation_widget.dart
- lib/features/children/family_history/widgets/pending_donation_widget.dart
- lib/l10n/arb/app_de.arb
- lib/l10n/arb/app_en.arb
- lib/l10n/arb/app_en_US.arb
- lib/l10n/arb/app_nl.arb
- Family goal history item (Givt) is implemented
> Feature/kids-534 Family goal history item (Givt)

- lib/core/network/api_service.dart
- lib/features/children/family_goal_tracker/cubit/goal_tracker_cubit.dart
- lib/features/children/family_goal_tracker/cubit/goal_tracker_state.dart
- lib/features/children/family_goal_tracker/model/family_goal.dart
- lib/features/children/family_goal_tracker/repository/goal_tracker_repository.dart
- lib/features/children/family_goal_tracker/widgets/goal_active_widget.dart
- lib/features/give/bloc/give/give_bloc.dart
- lib/features/give/bloc/give/give_event.dart
- lib/features/give/bloc/give/give_state.dart
- lib/features/give/models/givt_transaction.dart
- lib/features/give/pages/home_page.dart
- lib/features/give/pages/organization_list_page.dart
- lib/features/give/pages/select_giving_way_page.dart
- lib/features/give/widgets/choose_amount.dart
- lib/features/give/widgets/enter_amount_bottom_sheet.dart
- lib/features/give/widgets/home_goal_tracker.dart
- switched to the new api to fetch family goal (/latest instead of list)
- family goal widget is hidden from enter amount bottom sheet (but keep in home screen)
- other options of giving to family goal are hidden
- family goal id is passed to the transaction
> Feature: kids-508 Give to the family goal 

- lib/app/app.dart
- lib/app/routes/app_router.dart
- lib/features/children/family_goal_tracker/cubit/goal_tracker_cubit.dart
- Fetch family goal when user is authenticated
> Bug: kids-647 Fetch family goal when user is authenticated

- lib/core/network/api_service.dart
- lib/features/children/family_goal_tracker/repository/goal_tracker_repository.dart
> When 4xx error, assume a goal is not set yet (KIDS-665)

- lib/app/routes/app_router.dart
- lib/features/children/family_goal_tracker/cubit/goal_tracker_cubit.dart
- lib/features/children/family_goal_tracker/cubit/goal_tracker_state.dart
- lib/features/children/family_goal_tracker/pages/family_goal_tracker.dart
- lib/features/give/widgets/home_goal_tracker.dart
Goal tracker status assumed there is an activeGoal when the goal was simply fetched.
> Bug: Kids-643: Show correct goal state widget

- lib/features/children/family_goal/pages/create_family_goal_confirmed_page.dart
> Refresh Family Goal State after creating the goal (KIDS-675)

- lib/features/children/family_goal_tracker/cubit/goal_tracker_cubit.dart
> Bugfix: Clear state between fetches

- lib/app/routes/app_router.dart
> Bugfix: Fetch goal when navigating to family screen

- lib/features/give/widgets/collection_form_field.dart
> Add animation

- lib/core/enums/amplitude_events.dart
- lib/features/give/dialogs/give_to_family_goal_loading_dialog.dart
- lib/features/give/pages/select_giving_way_page.dart
- lib/features/give/widgets/enter_amount_bottom_sheet.dart
Additionally: 
- Loading dialog (at least as placeholder) is implemented; 
- Amplitude tracking added;
> Giving to the Family goal via Options page is implemented (KIDS-644)

- lib/features/give/widgets/choose_amount.dart
- lib/features/give/widgets/collection_form_field.dart
> Change color of active amount field (KIDS-503)

- lib/core/network/api_service.dart
> Increase TimeoutException duration to 30 seconds (KIDS-720)

- lib/features/give/dialogs/give_loading_dialog.dart
- lib/features/give/pages/bt_scan_page.dart
- lib/features/give/pages/gps_scan_page.dart
- lib/features/give/pages/select_giving_way_page.dart
- lib/features/give/widgets/enter_amount_bottom_sheet.dart
- GiveLoadingDialog (based on give to family goal loading dialog) is implemented; 
- Give via beacon is blocked by dialog; 
- Give via location is blocked by dialog; 
- Give via discovery is blocked by dialog;
> Block UI when donating (KIDS-645)

- lib/app/routes/app_router.dart
- lib/core/enums/amplitude_events.dart
- lib/features/auth/pages/email_signup_page.dart
- lib/features/auth/pages/login_page.dart
- lib/features/give/pages/organization_list_page.dart
- lib/features/give/widgets/choose_amount.dart
- lib/features/permit_biometric/cubit/permit_biometric_cubit.dart
- lib/features/permit_biometric/cubit/permit_biometric_state.dart
- lib/features/permit_biometric/models/permit_biometric_request.dart
- lib/features/permit_biometric/pages/permit_biometric_page.dart
- lib/features/registration/pages/credit_card_details_page.dart
- lib/features/registration/pages/gift_aid_request_page.dart
- lib/features/registration/pages/sign_sepa_mandate_page.dart
- lib/shared/widgets/custom_navigation_drawer.dart
- lib/utils/auth_utils.dart
- lib/utils/biometrics_helper.dart
- lib/utils/utils.dart
- Biometric reminder after login is implemented; 
- Login/Registration logic is slightly refactored; 
- Amplitude tracking is added;
> Suggestion to enable biometric after login is implemented (KIDS-692)

- lib/shared/pages/fingerprint_bottom_sheet.dart
- Save denied shared preferences setting when biometric switches off via the menu
> Givt app launches as expected after biometrics was switched off (KIDS-748)

- lib/app/routes/app_router.dart
> Revert change

- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/GoogleService-Info.plist
- ios/fastlane/Fastfile
- ios/firebase_app_id_file.json
- lib/app/bootstrap.dart
- lib/features/auth/repositories/auth_repository.dart
- pubspec.lock
- pubspec.yaml
> Add Crashlytics and upload symbols to Crashlytics for iOS

- lib/features/children/add_member/cubit/add_member_cubit.dart
- lib/features/children/add_member/models/member.dart
- lib/features/children/add_member/widgets/add_member_form.dart
- lib/l10n/arb/app_de.arb
- lib/l10n/arb/app_en.arb
- lib/l10n/arb/app_en_US.arb
- lib/l10n/arb/app_nl.arb
- Email and description added to the add member form; 
- Amplitude tracking extended with email;
> Add email and description to the add member form (KIDS-710, KIDS-713)

- lib/app/injection/injection.dart
- lib/app/routes/app_router.dart
- lib/app/routes/pages.dart
- lib/features/children/generosity_challenge/cubit/generosity_challenge_cubit.dart
- lib/features/children/generosity_challenge/cubit/generosity_challenge_state.dart
- lib/features/children/generosity_challenge/models/day.dart
- lib/features/children/generosity_challenge/pages/generosity_challenge.dart
- lib/features/children/generosity_challenge/pages/generosity_challenge_active_day.dart
- lib/features/children/generosity_challenge/pages/generosity_challenge_overview.dart
- lib/features/children/generosity_challenge/repositories/generosity_challenge_repository.dart
- lib/features/children/generosity_challenge/utils/generosity_challenge_helper.dart
- lib/features/children/generosity_challenge/widgets/day_item_placeholder.dart
- Generosity challenge skeleton is implemented; 
- Logic that activates challenge via secret link is implemented; 
- Logic that keeps user in the loop is implemented; 
- Placeholder pages for overview and active day are implemented;
> Generosity challenge closed loop is implemented (KIDS-751, KIDS-750, KIDS-755)

- lib/core/network/api_service.dart
- lib/features/give/pages/home_page.dart
- lib/features/impact_groups/cubit/impact_groups_cubit.dart
- lib/features/impact_groups/impact_group_recieve_invite_sheet.dart
- lib/features/impact_groups/models/impact_group.dart
> Use live endpoint (Kids-724)

- lib/shared/widgets/action_container.dart
> No feedback on pressed-down buttons (kids-780)

- lib/features/children/generosity_challenge/pages/generosity_challenge.dart
- lib/features/children/generosity_challenge/pages/generosity_challenge_overview.dart
> Refresh generosity challenge when app is re-opened (kids-779)

- lib/features/children/generosity_challenge/pages/generosity_challenge_day_details.dart
- lib/features/children/generosity_challenge/pages/generosity_challenge_overview.dart
> Fix amplitude tracking (kids-811)

- lib/core/network/api_service.dart
> Use endpoint to accept invitation (kids-724)

- lib/core/network/api_service.dart
- lib/features/give/pages/home_page.dart
- lib/features/impact_groups/cubit/impact_groups_cubit.dart
- lib/shared/models/user_ext.dart
> Show personal info registration screen to invited users (kids-822)

- lib/features/auth/cubit/auth_cubit.dart
> Do not show biometrics for temp users (kids-823)

- lib/shared/models/user_ext.dart
> Update invited user logic (kids-822)

- lib/features/impact_groups/cubit/impact_groups_cubit.dart
> do not fetch impact groups while already fetching

- README.md
Hey @MaikelStuivenberg,
I updated the README.md with 2 links to redirect to PlayStore and AppStore.
> Added download links

- .github/workflows/android.yml
> Temp fix to solve Android Release

- lib/core/enums/amplitude_events.dart
- lib/features/give/pages/select_giving_way_page.dart
> Give to the family goal is removed as a way of giving (KIDS-781)

- lib/features/give/pages/home_page.dart
- Ignore PageView's onPageChanged callback when inter-page animation is active
> Tab bar navigation issue is fixed (KIDS-895)

- lib/features/give/pages/organization_list_page.dart
- lib/features/impact_groups/pages/impact_group_details_page.dart
> Show offline success page (kids-905)

- lib/l10n/arb/app_de.arb
- lib/l10n/arb/app_en.arb
- lib/l10n/arb/app_en_US.arb
- lib/l10n/arb/app_nl.arb
> Bug duplicate 'Family Family'

- lib/features/give/pages/giving_page.dart
> Refetch groups after browser closure (kids-900)

- lib/features/children/generosity_challenge/assignments/family_values/pages/select_family_values_page.dart
- Doesnt align with design but Andy requested this
> Change the continue button to a FAB instead of bottom of column

- lib/features/children/generosity_challenge_chat/chat_scripts/widgets/chat_bubble.dart
> Show zoomed-in picture on tap in chat (kids-879)

- lib/features/children/generosity_challenge_chat/chat_scripts/widgets/chat_history.dart
> Switch chat bubble colors

- lib/features/children/generosity_challenge/cubit/generosity_challenge_cubit.dart
- lib/features/children/generosity_challenge/pages/generosity_challenge_overview.dart
- lib/features/children/generosity_challenge/repositories/generosity_challenge_repository.dart
- lib/features/children/generosity_challenge_chat/chat_scripts/cubit/chat_scripts_cubit.dart
remove future/async for method which doesnt need it + check cubit for user data
> Show family details on overview screen (KIDS-968)

- lib/features/children/generosity_challenge_chat/chat_scripts/models/enums/chat_script_function.dart
- pubspec.lock
- pubspec.yaml
> notification permission check & redirect (kids-880)

- lib/features/children/generosity_challenge/cubit/generosity_challenge_cubit.dart
- lib/features/children/generosity_challenge/cubit/generosity_challenge_state.dart
- lib/features/children/generosity_challenge/pages/generosity_challenge.dart
- lib/features/children/generosity_challenge/widgets/mayor_chat_dialog.dart
> Show Mayor Chat Dialog when Day is completed (KIDS-875)

- lib/features/children/generosity_challenge/pages/generosity_challenge_overview.dart
> Open chat when available (KIDS-970)

- assets/jsons/generosity_challenge/chat_scripts/chat_script_day_0.json
- assets/jsons/generosity_challenge/chat_scripts/chat_script_day_1.json
- assets/jsons/generosity_challenge/chat_scripts/chat_script_day_3.json
- lib/features/children/generosity_challenge_chat/chat_scripts/models/enums/chat_script_save_key.dart
> Update script + Asking for child age

- lib/features/registration/widgets/registered_check_animation.dart
> Fix registered icons not showing correctly.

- assets/jsons/generosity_challenge/chat_scripts/chat_script_day_5.json
> Add answerText

- lib/features/children/generosity_challenge_chat/chat_scripts/pages/chat_script_page.dart
> Close button only on dev

- lib/features/children/generosity_challenge_chat/chat_scripts/widgets/chat_bar.dart
- lib/shared/widgets/givt_elevated_button.dart
> Align multiline text to center on buttons

- lib/features/children/add_member/widgets/add_member_form.dart
- lib/features/children/add_member/widgets/allowance_counter.dart
Currently this widget is only being used in the add member page. I want to use this same widget on the new edit monthly giving allowance screen.
> Extract allowance counter as a reusable widget. 

- assets/jsons/generosity_challenge/chat_scripts/chat_script_day_6.json
- lib/features/children/generosity_challenge_chat/chat_scripts/models/enums/chat_script_function.dart
> Add pre/post chat script day 7 (KIDS-947)

- lib/app/routes/app_router.dart
- lib/features/children/generosity_challenge/cubit/generosity_challenge_cubit.dart
- lib/features/children/generosity_challenge/pages/generosity_challenge_overview.dart
- lib/features/children/generosity_challenge/repositories/generosity_challenge_repository.dart
- lib/features/children/generosity_challenge/widgets/day_button.dart
- on long pressed callback is added to the Day button (dev only)
- undo challenge progress per day (both days status and chat history) logic is implemented
- simple confirmation dialog is implemented
- note: saved user data stays in the prefs and should be overwritten later on by the chat
>  Undo challenge progress per day is implemented (KIDS-980)

- lib/features/children/generosity_challenge/pages/generosity_challenge_overview.dart
- lib/features/children/generosity_challenge/widgets/day_button.dart
- enable undo logic for dev app by checking package name instead of using kDebugMode
> Enable undo logic for dev app (fix for KIDS-980)

- lib/features/children/generosity_challenge/cubit/generosity_challenge_cubit.dart
Next available day should become available after midnight not after 24 hours.
> Bug fix: next available day is after midnight not after 24 hours

- assets/jsons/generosity_challenge/chat_scripts/chat_script_day_6.json
- lib/app/injection/injection.dart
- lib/core/enums/amplitude_events.dart
- lib/core/network/api_service.dart
- lib/features/auth/cubit/auth_cubit.dart
- lib/features/auth/models/session.dart
- lib/features/auth/repositories/auth_repository.dart
- lib/features/children/generosity_challenge/cubit/generosity_challenge_cubit.dart
- lib/features/children/generosity_challenge/utils/generosity_challenge_content_helper.dart
- lib/features/children/generosity_challenge_chat/chat_scripts/cubit/chat_scripts_cubit.dart
- lib/features/children/generosity_challenge_chat/chat_scripts/models/enums/chat_script_function.dart
- lib/features/children/generosity_challenge_chat/chat_scripts/utils/chat_script_registration_handler.dart
https://linear.app/givt/issue/KIDS-941/implement-registration
> Feature: Implement Day 7 chat registration (kids-941)

- assets/jsons/generosity_challenge/chat_scripts/chat_script_day_7.json
- lib/features/children/generosity_challenge/repositories/generosity_challenge_repository.dart
- lib/features/children/generosity_challenge/utils/generosity_challenge_content_helper.dart
- lib/features/children/generosity_challenge/utils/generosity_challenge_helper.dart
- lib/features/children/generosity_challenge/widgets/day_button.dart
> Add day 8 to the overview (Kids-994)

- lib/features/children/generosity_challenge/assignments/create_challenge_donation/widgets/slider_widget.dart
- pubspec.lock
- activeTickMarkColor: Colors.transparent;
- inactiveTickMarkColor: Colors.transparent;
> Hotfix - make slider's tickMarkColors transparent

- lib/core/enums/amplitude_events.dart
- lib/features/children/details/pages/child_details_page.dart
- lib/features/children/details/widgets/child_top_up_card.dart
- lib/l10n/arb/app_de.arb
- lib/l10n/arb/app_en.arb
- lib/l10n/arb/app_en_US.arb
- lib/l10n/arb/app_nl.arb
> Feature implement top up card (kids-842)

- lib/app/routes/app_router.dart
- lib/features/children/generosity_challenge/cubit/generosity_challenge_cubit.dart
- lib/features/children/generosity_challenge/pages/generosity_challenge.dart
- lib/features/children/generosity_challenge/pages/generosity_challenge_overview.dart
- lib/features/children/generosity_challenge/repositories/generosity_challenge_repository.dart
- lib/features/children/generosity_challenge/utils/generosity_challenge_helper.dart
- completeChallenge method added to the GenerosityChallengeCubit; 
- clear user data logic is implemented; 
- prevent user to start challenge if it was already completed logic is implemented; 
- challenge completion trigger with navigation to the Givt app is implemented (kids-993); 
- complete challenge button (for dev builds only) with confirmation dialog is implemented;
> Generosity challenge completion with navigation to the Givt app (KIDS-958, KIDS-993)

- lib/features/children/generosity_challenge/cubit/generosity_challenge_cubit.dart
> Hack: disable day 8

- lib/features/children/details/pages/child_details_page.dart
> hotfix: hide to up card

- lib/features/children/generosity_challenge/cubit/generosity_challenge_cubit.dart
> Revert "Hack: disable day 8"

- lib/features/children/details/cubit/child_details_cubit.dart
- lib/features/children/details/pages/child_details_page.dart
also make top up visible again
> Bug: kids 1010 top up success grey screen

- assets/jsons/generosity_challenge/chat_scripts/chat_script_day_1.json
https://linear.app/givt/issue/KIDS-1014/add-tracking-for-no-answers-in-day-2
> Add tracking for no answers in day 2.

- .github/workflows/main.yaml
- lib/features/children/add_member/cubit/add_member_cubit.dart
- lib/features/children/add_member/pages/add_member_form_page.dart
- lib/features/children/add_member/widgets/add_member_form.dart
- lib/features/children/details/pages/child_details_page.dart
- pubspec.lock
- pubspec.yaml
> Production release 4.2.19

- lib/features/registration/pages/signup_page.dart
> US-Only - Update signup page with phone number field (KIDS-974)

- lib/features/registration/pages/signup_page.dart
> Bugfix: Validate form when changing phonenr (KIDS-974)

- ios/Runner/Runner.entitlements
- ios/fastlane/report.xml
> Lets try some apple pay things again

- lib/features/children/details/pages/child_details_page.dart
- lib/features/children/family_history/family_history.dart
- lib/features/children/family_history/models/history_item.dart
- lib/features/children/family_history/models/topup.dart
- lib/features/children/family_history/repository/family_history_repository.dart
- lib/features/children/family_history/widgets/topup_item_widget.dart
- pubspec.lock
> Add topup item to history (kids-854)

- lib/app/routes/app_router.dart
- lib/features/children/edit_child/repositories/edit_child_repository.dart
- lib/features/children/family_history/family_history_cubit/family_history_cubit.dart
https://linear.app/givt/issue/KIDS-1066/when-the-top-up-fails-in-the-g4k-it-shows-awesome-while-it-should-show
> Bugfix: Family history doesn't update after topup (KIDS-1067)

- lib/features/children/generosity_challenge/widgets/generosity_challenge_daily_card.dart
https://linear.app/givt/issue/KIDS-1006/when-i-skip-in-the-end-it-still-want-me-to-setup-recurring-allowance
> Bugfix: Clicking skip on day 8 sometimes goes to the wrong flow (KIDS-1006)

- .github/workflows/main.yaml
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/Runner.entitlements
- ios/fastlane/report.xml
- lib/app/routes/app_router.dart
- lib/core/notification/notification_service.dart
- lib/features/children/add_member/cubit/add_member_cubit.dart
- lib/features/children/add_member/pages/add_member_form_page.dart
- lib/features/children/add_member/widgets/add_member_form.dart
- lib/features/children/details/cubit/child_details_cubit.dart
- lib/features/children/details/models/profile_ext.dart
- lib/features/children/details/pages/child_details_page.dart
- lib/features/children/details/widgets/child_details_item.dart
- lib/features/children/edit_child/repositories/edit_child_repository.dart
- lib/features/children/family_history/family_history.dart
- lib/features/children/family_history/family_history_cubit/family_history_cubit.dart
- lib/features/children/family_history/models/history_item.dart
- lib/features/children/family_history/models/topup.dart
- lib/features/children/family_history/repository/family_history_repository.dart
- lib/features/children/family_history/widgets/topup_item_widget.dart
- lib/features/children/generosity_challenge/widgets/generosity_challenge_daily_card.dart
- lib/features/children/overview/models/profile.dart
- lib/features/registration/pages/signup_page.dart
- pubspec.lock
- pubspec.yaml
> Prod release 4.2.20

- lib/app/routes/app_router.dart
- lib/features/give/pages/home_page.dart
> Shorten registration flow US (KIDS-1045)

- lib/app/routes/app_router.dart
- lib/features/registration/pages/registration_success_us.dart
> Update RegistrationSuccess US screen and redirect after screen to AddMember page (KIDS-1046)

- lib/features/family/features/home_screen/widgets/home_screen_app_bar.dart
- lib/features/family/shared/widgets/common_icons.dart
> Update change profile icon  (KIDS-1077)

- lib/features/auth/cubit/auth_cubit.dart
- lib/features/auth/repositories/auth_repository.dart
- lib/features/family/features/profiles/cubit/profiles_cubit.dart
- lib/features/family/features/profiles/screens/profile_selection_screen.dart
- lib/utils/analytics_helper.dart
https://linear.app/givt/issue/KIDS-1055/improve-amplitude-implementation-for-1app
> Feature: 1app amplitude tracking improvements (KIDS-1055)

- lib/app/routes/app_router.dart
- lib/app/routes/pages.dart
- lib/features/family/app/pages.dart
- lib/features/family/app/routes.dart
- lib/features/family/features/profiles/cubit/profiles_cubit.dart
- lib/features/family/features/profiles/cubit/profiles_state.dart
- lib/features/family/features/profiles/screens/profile_selection_screen.dart
- lib/features/registration/pages/credit_card_details_page.dart
- lib/features/registration/pages/signup_page.dart
- lib/features/registration/widgets/registration_app_bar.dart
https://linear.app/givt/issue/KIDS-1104/prevent-users-from-backing-out-of-us-registration
Also fixed a bug where sometimes we navigated to the personal info sign up page instead of the credit card registration.
> Feature: prevent users from backing out of registration flow US (KIDS-1104)

- .github/workflows/main.yaml
> Cancel only builds per branch

- .github/workflows/android.yml
- .github/workflows/ios.yml
- .github/workflows/main.yaml
- lib/core/logging/log_message.dart
- lib/core/logging/logging_service.dart
- lib/core/network/token_interceptor.dart
- lib/features/give/pages/bt_scan_page.dart
- pubspec.yaml
> Production release 4.2.22

- .github/workflows/android.yml
> Upload production build to internal test.

- lib/features/children/add_member/pages/add_member_form_page.dart
> Navigate to childrenoverview on registration success rather than profile selection screen.

- lib/features/family/features/profiles/screens/profile_selection_screen.dart
- lib/features/family/features/profiles/widgets/profiles_empty_state_widget.dart
> Logout button when no profiles available (KIDS-1117)

- lib/core/enums/amplitude_events.dart
- lib/core/network/api_service.dart
- lib/features/children/add_member/widgets/allowance_counter.dart
- lib/features/children/details/cubit/child_details_cubit.dart
- lib/features/children/details/cubit/child_details_state.dart
- lib/features/children/details/pages/child_details_page.dart
- lib/features/children/details/widgets/child_cancel_rga_failed_dialog.dart
- lib/features/children/details/widgets/child_cancel_rga_success_dialog.dart
- lib/features/children/details/widgets/child_details_item.dart
- lib/features/children/details/widgets/child_giving_allowance_card.dart
- lib/features/children/details/widgets/child_top_up_card.dart
- lib/features/children/edit_child/repositories/edit_child_repository.dart
- lib/features/children/overview/pages/add_top_up_page.dart
- lib/features/children/overview/pages/edit_allowance_page.dart
- lib/features/children/overview/widgets/cancel_allowance_dialog.dart
- lib/features/children/overview/widgets/edit_allowance_widget.dart
- lib/features/family/utils/family_app_theme.dart
- lib/shared/widgets/buttons/custom_green_elevated_button.dart
- lib/shared/widgets/common_icons.dart
- lib/shared/widgets/theme/app_theme_switcher.dart
- lib/utils/app_theme.dart
> Feature Allow cancelling the RGA (Kids-1089)

- android/app/src/main/AndroidManifest.xml
- lib/app/routes/app_router.dart
- pubspec.yaml
> Prod release (v4.3.2)

- lib/shared/pages/gift_aid_page.dart
> Fix: update gift-aid switch color (kids-890)

- lib/features/registration/pages/registration_success_us.dart
> Fix typo (kids-1142)

- lib/features/children/generosity_challenge/pages/generosity_challenge_overview.dart
- lib/features/family/app/family_routes.dart
- lib/features/family/features/scan_nfc/nfc_scan_screen.dart
- pubspec.yaml
> Prod release 4.3.7

- lib/features/children/generosity_challenge/cubit/generosity_challenge_cubit.dart
- lib/features/children/generosity_challenge/pages/generosity_challenge_day_details.dart
- lib/features/children/generosity_challenge/pages/generosity_challenge_overview.dart
> Enhancement: Enable next day immediately (kids-1230)

- lib/utils/util.dart
https://linear.app/givt/issue/KIDS-1245/improve-the-email-address-validation-to-avoid-problems-for-users
> Feature: improve email validation (KIDS-1245)

- lib/features/registration/widgets/accept_policy_row_us.dart
- lib/features/registration/widgets/stripe_info_sheet.dart
> fix: bottomsheet styling (kids-1309)

- lib/features/family/features/profiles/repository/profiles_repository.dart
- pubspec.yaml
> release to prod bugfix v 4.4.1

- lib/l10n/arb/app_de.arb
- lib/l10n/arb/app_en.arb
- lib/l10n/arb/app_en_US.arb
- lib/l10n/arb/app_es.arb
- lib/l10n/arb/app_es_419.arb
- lib/l10n/arb/app_nl.arb
Pull Request triggered from POEditor
> Pull Request triggered from POEditor

- pubspec.yaml
PR is only for release note purposes
> Translate homescreen + registration to spanish
